# Generated by Django 3.1.3 on 2020-12-07 20:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='body',
            field=wagtail.core.fields.StreamField([]),
        ),
    ]
