# Generated by Django 3.1.3 on 2020-12-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201219_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='what_client_say_text',
            field=models.CharField(max_length=500),
        ),
    ]
